#Component Info
info:
 component: zuul-server
 
#Spring Application Name 
spring:
 application:
  name: zuul-server
 
#Server Port
server:
 port: 8080

#Eureka Instance ID
eureka:
 instance:
  instanceId: ${spring.application.name}:${server.port}-${spring.application.instance_id:${random.value}}

#Ribbon Activation
ribbon:
 eureka:
  enabled: true
  
#Routers
zuul:
  routes:
    users:
      path: /user/**
      serviceId: user-services    
    customer:
      path: /customer/**
      serviceId: customer-services
    product:
      path: /product/**
      serviceId: product-services      
      